name: Deploy to Reg.ru

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
    
    - name: Create deployment archive
      run: |
        mkdir -p deploy
        cp -r dist/* deploy/
        mkdir -p deploy/api
        cp -r api/* deploy/api/
        cp *.php deploy/ 2>/dev/null || true
        tar -czf site.tar.gz -C deploy .
        
    - name: Deploy files
      run: |
        find deploy -type f -name "*.php" -exec curl -T {} ftp://31.31.197.14/www/myrentology.ru/{} --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs \;
        find deploy -type f -name "*.html" -exec curl -T {} ftp://31.31.197.14/www/myrentology.ru/{} --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs \;
        find deploy -type f -name "*.js" -exec curl -T {} ftp://31.31.197.14/www/myrentology.ru/{} --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs \;
        find deploy -type f -name "*.css" -exec curl -T {} ftp://31.31.197.14/www/myrentology.ru/{} --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs \;
        find deploy -type f -name ".htaccess" -exec curl -T {} ftp://31.31.197.14/www/myrentology.ru/{} --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs \;