name: Deploy to Reg.ru

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
    
    - name: Deploy via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 31.31.197.14
        username: u3304368
        password: Jb50va7up7SLBTOv
        local_path: './dist/*'
        remote_path: '/www/myrentology.ru/'
        
    - name: Deploy API via SFTP
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: 31.31.197.14
        username: u3304368
        password: Jb50va7up7SLBTOv
        local_path: './api/*'
        remote_path: '/www/myrentology.ru/api/'