name: Deploy to Reg.ru

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
    
    - name: Create deployment archive
      run: |
        mkdir -p deploy
        cp -r dist/* deploy/
        mkdir -p deploy/api
        cp -r api/* deploy/api/
        tar -czf site.tar.gz -C deploy .
        
    - name: Deploy via curl
      run: |
        for file in deploy/*; do
          if [ -f "$file" ]; then
            curl -T "$file" ftp://31.31.197.14/www/myrentology.ru/ --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs || echo "Failed to upload $file"
          fi
        done
        
        for file in deploy/api/*; do
          if [ -f "$file" ]; then
            curl -T "$file" ftp://31.31.197.14/www/myrentology.ru/api/ --user "u3304368:Jb50va7up7SLBTOv" --ftp-create-dirs || echo "Failed to upload $file"
          fi
        done